# -*- coding: utf-8 -*-
"""rdb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1znLVqHGsZO7AE7yqPmdyoKlBK1tbt1MR
"""

from rdblearn.datasets import RDBDataset
from rdblearn.estimator import RDBLearnRegressor
from tabpfn import TabPFNRegressor
import pandas as pd

# 1. Load RelBench dataset and task
dataset = RDBDataset.from_relbench("rel-avito")
task = dataset.tasks["ad-ctr"]

# 2. Initialize the estimator with a base model (e.g., TabPFN)
#    Both enable_target_augmentation and temporal_diff are enabled by default.
reg = RDBLearnRegressor(
    base_estimator=TabPFNRegressor(device="cuda"), # or "cuda"
    config={
        "dfs": {"max_depth": 2},
        "enable_target_augmentation": True,
        "temporal_diff": {"enabled": True},
        "max_train_samples": 1000
    }
)

# 3. Fit on relational data
X_train = task.train_df.drop(columns=[task.metadata.target_col])
y_train = task.train_df[task.metadata.target_col]

print("Raw train shape:", X_train.shape)
print("Raw columns:", list(X_train.columns))

reg.fit(
    X=X_train,
    y=y_train,
    rdb=dataset.rdb,
    key_mappings=task.metadata.key_mappings,
    cutoff_time_column=task.metadata.time_col
)


print("Finished fit")

if "autogluon" in reg.preprocessor_.pipeline.named_steps:
    ag = reg.preprocessor_.pipeline.named_steps["autogluon"]

    print("type(ag):", type(ag))
    print("----- ag attrs containing feature/column -----")
    for attr in dir(ag):
        low = attr.lower()
        if ("feature" in low) or ("column" in low):
            print(attr)

    print("----- ag.__dict__.keys() -----")
    if hasattr(ag, "__dict__"):
        print(ag.__dict__.keys())

    if hasattr(ag, "feature_generator_"):
        fg = ag.feature_generator_
        print("type(feature_generator_):", type(fg))

        print("----- feature_generator attrs containing feature/column/output -----")
        for attr in dir(fg):
            low = attr.lower()
            if ("feature" in low) or ("column" in low) or ("output" in low):
                print(attr)

        print("----- feature_generator __dict__.keys() -----")
        if hasattr(fg, "__dict__"):
            print(fg.__dict__.keys())
else:
    print("No autogluon step found")

fg = ag.feature_generator_

print("Input features:", fg.features_in)
print("Output feature count:", len(fg.features_out))
print("Example output features:", fg.features_out[:30])
# 4. Predict
X_test = task.test_df.drop(columns=[task.metadata.target_col])
y_test = task.test_df[task.metadata.target_col]

predictions = reg.predict(X=X_test)

df_pred = pd.DataFrame({
    "y_true": y_test,
    "y_pred": predictions
})

df_pred.to_csv("predictions.csv", index=False)

print("Saved predictions.csv")